Add check for PGP signed tags to release workflow
Signed-off-by: Stefan Prodan <stefan.prodan@gmail.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -36,8 +36,8 @@ jobs:
       - name: Verify signed release
         if: startsWith(github.ref, 'refs/tags/v')
         run: |
-          git -P show ${{ github.event.inputs.tag }} | grep -q 'PGP SIGNATURE' || \
-          { echo "No PGP signature found for tag ${{ github.event.inputs.tag }}. Aborting release process..."; exit 1; }
+          git -P show ${GITHUB_REF_NAME} | grep -q 'PGP SIGNATURE' || \
+          { echo "No PGP signature found for tag $GITHUB_REF_NAME}. Aborting release process..."; exit 1; }
       - name: Prepare
         id: prep
         run: |
